### ISSUE TITLE
Epic 0: Reconciliation of Adventist Discovered Issues with Hyku/Knapsack

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#112]
## Tasks
- [x] Hyku `adventist_dev` branch needs reviewing/merging into Hyku `main`
- [ ] https://github.com/scientist-softserv/adventist_knapsack/issues/60 (head's up we might have problems)
- [ ] https://github.com/samvera-labs/hyku_knapsack/issues/1 (head's up we might have problems)
- [ ] #113

**Comment by ShanaLMoore** [comment]
Rob estimates this will be complete by EOD today.
