### ISSUE TITLE
☄ [EPIC] Adventist Theme Work

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#281]
# Summary
~~Adventist knapsack doesn't look like it should because the concept of themes is new to them. We need to create an adventist theme for their hyku upgrade.~~

A custom theme might be ideal, but would be far too much work. Instead for now, the custom CSS and views will be used. Future work could revert some of the customization and move to themes, but that is beyond the scope of this upgrade.

# Acceptance Criteria
~~A user should be able to switch to this theme and make the app look like Adventist staging.~~

The view should look like Adventist staging. 

# Screenshot
![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/b69930e1-fbeb-455e-b3a8-e96ad93b25da)

# Notes
As a result of doing so, hopefully the following issues will get fixed too:
- [x] scientist-softserv/adventist-dl#572 
- [x] scientist-softserv/adventist-dl#562 
- [ ] ~#580~ removed from sprint since this is not a behavior caused by the knapsack work
