### ISSUE TITLE
Slug is stored in alternative_title field

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#287]
Alternative title and slug are using the same predicate, and are saved in Fedora into alternative. This causes the potential for errors.

The UI behavior does not seem to allow incorrect data. So based on behavior as listed below, a simple mitigation seems adequate, rather than changing the predicate and doing a full migration as would be the correct way. There is a potential for erroneous behavior if alternative_id is used in Bulkrax? This has not yet been tested.

Behavior observed via UI:
- When a work is added through the UI, alternative title is ignored & overwritten by aark_id => turned into slug, based most likely on the sequence of terms on the form
- When attempting to edit the work, the slug will show in alternative title field on the edit form
- Adding a second alternative title option is present but causes errors.
- Unable to edit the first alternative title - changes do not save
- Slug changes and is propagated into alternative title when aark_id is updated
- Updated slug works correctly, replacing the prior slug

# Tasks
- [x] Remove alternative title from the forms so it can't be entered or edited
- [x] Make sure bulkrax doesn't map anything into Alternative Title. 
- [x] Verify that behavior is correct for all work types.

# Testing

Verify that you can create or edit each work type, and alternative_title term is not on the forms.

<details>
<summary>Results of adding another alternative title</summary>

**After attempting to add a second Alternative title:**
![Image](https://github.com/scientist-softserv/adventist-dl/assets/17851674/54ebd039-5070-45b7-b731-b9246a41afde)

</details>
