### ISSUE TITLE
☄️ Epic: Failing Specs

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#324]
## Summary
Specs will be likely failing after scientist-softserv/adventist-dl#537 and we would like to get them passing again to avoid missing issues in the app.

- scientist-softserv/adventist-dl#537 

## Accepted Criteria
- [x] Follow up tickets are created for failing specs

## Testing Instructions
run specs from the knapsack directory, not hyrax-webapp

Per Rob 

"I did check on [this](https://assaydepot.slack.com/archives/C0311DN2YCA/p1696257247115929?thread_ts=1696136499.049409&cid=C0311DN2YCA) and got the specs to run. The way things are set up it does run the Hyku specs too but it allows you to override any spec file by making one the same path / name. So for example if the generic work specs fail because you changed the properties on it. You would make a generic work spec in the knapsack and that would override the Hyku version."

# Failures

Ran specs off of:

- https://github.com/scientist-softserv/adventist_knapsack/pull/19

CROSS OUT = SPECS REMOVED

- [x] rspec ./spec/forms/hyrax/generic_work_form_spec.rb:27 # Hyrax::GenericWorkForm.terms returns an array of inherited and custom terms
- [x] rspec ./spec/models/image_spec.rb:10 # Image indexer 
- [x] ~rspec ./spec/features/labels_spec.rb:54 # Site labels configuration as an administrator institution name full updates the full institution name in the agreement text~
- [x] ~rspec ./spec/features/labels_spec.rb:12 # Site labels configuration as an administrator application name updates the application name in the brand bar~
- [x] ~rspec ./spec/features/labels_spec.rb:19 # Site labels configuration as an administrator application name updates the application name in the~ <head> <title>
- [x] ~rspec ./spec/features/labels_spec.rb:36 # Site labels configuration as an administrator institution name updates the institution name in the agreement text~
- [x] ~rspec ./spec/features/accounts_spec.rb:27 # Accounts administration as an superadmin changes the associated cname~ (Removed because it's not testing specific to adventist behavior)
- [x] ~rspec ./spec/features/accounts_spec.rb:39 # Accounts administration as an superadmin changes the account service endpoints~ (Removed because it's not testing specific to adventist behavior)
- [x] rspec ./spec/search_builders/adv_search_builder_spec.rb:55 # AdvSearchBuilder.default_processor_chain is expected to eq [:default_solr_parameters, :add_query_to_solr, :add_facet_fq_to_solr, :add_facetting_to_solr, :add_so...ccess, :exclude_models, :highlight_search_params, :show_parents_only, :include_allinson_flex_fields]
- [x] ~rspec ./spec/features/roles_spec.rb:12~ # Site Roles as an administrator lists user roles
- [x] ~rspec ./spec/features/roles_spec.rb:19~ # Site Roles as an administrator updates user roles
- [x] rspec ./spec/forms/hyrax/image_form_spec.rb:28 # Hyrax::ImageForm.terms returns an array of inherited and custom terms
- [x] ~rspec ./spec/features/contact_spec.rb:12 # Site contact configuration as an administrator application name updates the application name in the brand bar~
- [x] rspec ./spec/presenters/hyku/admin/group/navigation_presenter_spec.rb:35 # Hyku::Admin::Group::NavigationPresenter with members page has 3 tabs
- [x] rspec ./spec/presenters/hyku/admin/group/navigation_presenter_spec.rb:51 # Hyku::Admin::Group::NavigationPresenter with remve page has 3 tabs
- [x] rspec ./spec/presenters/hyku/admin/group/navigation_presenter_spec.rb:19 # Hyku::Admin::Group::NavigationPresenter with edit page has 3 tabs
- [x] rspec ./spec/controllers/hyrax/hyrax/generic_works_controller_spec.rb:23 # Hyrax::GenericWorksController#presenter initializes a presenter
- [x] rspec ./spec/controllers/hyrax/hyrax/admin/appearances_controller_spec.rb:30 # Hyrax::Admin::AppearancesController with an administrator GET #show assigns the requested site as @site
- [x] rspec ./spec/services/adventist/text_file_text_extraction_service_spec.rb:24 # Adventist::TextFileTextExtractionService position in the array of Hyrax::DerivativeService.services is in the first position
- [x]  rspec ./spec/models/user_spec.rb:11 # User the first created user in global tenant does not get the admin role
- [x] rspec ./spec/models/user_spec.rb:47 # User#site_roles= assigns global roles to the user
- [x] rspec ./spec/models/user_spec.rb:39 # User#site_roles fetches the global roles assigned to the user
- [x] rspec ./spec/models/user_spec.rb:30 # User a subsequent user does not get the admin role
- [x] rspec ./spec/models/user_spec.rb:20 # User the first created user on a tenant is given the admin role
- [x] ~rspec ./spec/models/hyrax/contact_form_spec.rb:30~ # Hyrax::ContactForm headers site email set uses the Site email
- [x] ~rspec ./spec/models/hyrax/contact_form_spec.rb:21~ # Hyrax::ContactForm headers no email set uses the hyrax setting
- [x] ~rspec ./spec/models/bulkrax/csv_entry_spec.rb:79~ # Bulkrax::CsvEntry#build_metadata assigns factory_class and parsed_metadata
- [x] rspec ./spec/controllers/hyrax/hyrax/images_controller_spec.rb:28 # Hyrax::ImagesController#presenter initializes a presenter
