### ISSUE TITLE
☄️ Go Live Checklist for Adventist Pre-Processing

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist_knapsack#343]
The following items are required as part of starting the pre-processing of Adventist's objects (Note this is a living list, we may read it and need to add more):

- [x] Confirm that Adventist wants to split PDFs into JPGs.  (The goal is to minimize storage costs.)
  - Confirmed as viable via https://github.com/scientist-softserv/adventist-dl/issues/379
  - Conversation with @KatharineV in the past have indicated being mindful of storage costs; JPGs are the lower file size option
- [x] Ensure that Adventist’s SpaceStone configuration is splitting pages into JPGs
- [x] Ensure that Adventist’s DerivativeRodeo (by way of IIIF Print) configuration is looking for JPGs  
- [x] scientist-softserv/adventist-dl#511
- [x] scientist-softserv/adventist-dl#512
  - [x] https://github.com/scientist-softserv/derivative_rodeo/issues/67
- [x] scientist-softserv/adventist-dl#513 
- [x] scientist-softserv/adventist-dl#514
- [ ] https://github.com/scientist-softserv/derivative_rodeo/issues/69
- [ ] https://github.com/scientist-softserv/derivative_rodeo/issues/68
- [x] scientist-softserv/adventist-dl#515
- [x] scientist-softserv/adventist_knapsack#227
- [ ] scientist-softserv/adventist_knapsack#228
- [ ] scientist-softserv/adventist_knapsack#224
