### ISSUE TITLE
🧹Epic: SDAPI collections

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#371]
# Story

After errors have been handled ref 
- scientist-softserv/adventist-dl#436 
- scientist-softserv/adventist-dl#437

per [Kirk's comment](https://assaydepot.slack.com/archives/C0311DN2YCA/p1686082652604149) we need to: 

- [x] scientist-softserv/adventist-dl#442

  - She has students currently using this collection for work
As an aside, we’ve assigned b1432319 as the identifier for this one which will be included on her CSV

- [x] scientist-softserv/adventist_knapsack#369

  - After reviewing it with her, all she is really interested in is the bare essentials to get them created
identifier, model, title
  - [x] scientist-softserv/adventist_knapsack#367 

- [x] scientist-softserv/adventist_knapsack#368
  - is there a way to only import two columns so that it does not try to change the metadata? It should only run relationships. 
  - blocked need to fix majority of the errors??

  - We were looking at a way to maybe short circuit a Bulkrax import to achieve this scientist-softserv/adventist_knapsack#366 

# Acceptance Criteria

- [ ] Collections have been created in production.
- [ ] Records have established relationships with Collections in production.

# NOTES

[SDAPI_periodical_collections.xlsx](https://github.com/scientist-softserv/adventist-dl/files/11725786/SDAPI_periodical_collections.xlsx)
