### ISSUE TITLE
Spike: Identify What Must Change to Leverage Pre-Processing of the Rodeo

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist_knapsack#406]
The goal of this spike is to review the Derivative Rodeo, Bulkrax Implementation, Adventist Overrides, and IIIF Print to establish an approach on leveraging the pre-processed files instead of running the pre-processing inline.

From this spike will flow a set of tasks to complete the integration of the Derivative Rodeo pre-processing with the ingest process for Adventist.

## Use Cases and Questions

```gherkin
Given that the Derivative::Rodeo will have downloaded the <original file>
And that the Derivative::Rodeo has pre-processed the derivatives
When I am using Bulkrax to import a record with a remote <original file>
Then I need to instead use the <original file> now in the Derivative::Rodeo
```

Questions: 

- How could Bulkrax know that the `<original file>` is in the Derivative::Rodeo?
- What are our options for treating the Derivative::Rodeo files as mounted storage?
- Particularly in S3, what would it mean to move the file from the `Derivative::Rodeo` to a Fedora aware location?
  - What affordances do we have in that data transfer?

## Tasks

- [x] https://github.com/scientist-softserv/iiif_print/issues/218
- [ ] https://github.com/scientist-softserv/iiif_print/issues/219
- [ ] https://github.com/scientist-softserv/iiif_print/issues/220
