### ISSUE TITLE
EPIC: Import Optimization with Out of Band Processing

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist_knapsack#421]
<details>
<summary>Goals</summary>

The goal of this epic is to adjust the derivative “creation” process.

At present Hyrax creates a `FileSet` for each file added to a work either via the UI or via batch processing.  We then process each original file of a `FileSet` creating derivative files that we attach to that `FileSet`.  This is all done “in-band”, which can be non-performant for large imports.

To speed up the imports we can:

-   add more resources to the import system
-   perform “out of band” processing to generate derivatives

By introducing the idea of the “out of band” processing, we break the fundamental assumption of Hyrax’s derivative generation.  Namely that it will take a `FileSet` and create all the necessary derivatives.  Instead, with pre-processing, we are now saying “There may already exist a derivative for this `FileSet`, attach that instead.”

Instead of having one conceptual “Create Derivatives” function we are looking to have three:

-   **Pre-processing:** doing out of band work to create derivatives.
-   **Locating:** Finding the existing derivatives (or possibly indicating that we’d create new ones).
-   **Applying:** Taking the found derivative and adding it to the correct FileSet.

We have a “prior art” instance of *Pre-processing* in the [SpaceStone](https://github.com/scientist-softserv/space_stone) Ruby gem.  That gem is code that runs in <abbr title="Amazon Web Services">AWS</abbr> Lambdas to pull data from Internet Archive (per the client’s previous storage), split apart the PDFs, create <abbr title="Optical Character Recognition">OCR</abbr> derivatives of each page, and create thumbnails.

Further, we have “prior art” for *Locating* and *Applying* `.hocr` files in [NNP’s Tesseract module](https://github.com/scientist-softserv/nnp/blob/78206122b9796a79f07f349ef27babc167006f6d/app/services/tesseract.rb); responsible for first looking for a remote `.hocr` and failing that generating the `.hocr` file.

We have some logic for finding the *Pre-processing* files in [NNP’s DistributedRemoteDownloader](https://github.com/scientist-softserv/nnp/blob/78206122b9796a79f07f349ef27babc167006f6d/app/services/distributed_remote_downloader.rb).

Those are specific implementations that demonstrate some of the necessary concepts.  However, those are different from the immediate needs of Adventist and the general needs of other clients.

</details>

<details>
<summary>Scenarios</summary>

In terms of *Pre-Processing* we need the following:

```gherkin
Scenario: Pre-processing
Given an identifier for a FileSet
  And a URL to the original file
  And the file is a PDF
When I pass the identifier and URL to an AWS lambda
Then the Pre-processer Lambda will create one <JPG> per PDF page
  And the Pre-processer Lambda will create one HOCR per PDF page
  And the Pre-processer Lambda will create one Thumbnail per PDF page
```

In terms of *Locating* we need the following:

```gherkin
Scenario: Locating derivatives that were pre-processed
Given an identifier for a FileSet
  And the Pre-processer Lambda has processed the FileSet
When I attempt to locate the <JPGs, HOCRs, Thumbnails> for the split pages
Then I will get the location of the S3 files

Scenario: Locating derivatives that were not pre-processed
Given an identifier for a FileSet
  And the Pre-processer Lambda has not processed the FileSet
When I attempt to locate the <JPGs, HOCRs, Thumbnails> for the split pages
Then I will not get a location of the S3 files
  And I will get a “location” that will indicate to use the default Hyrax derivative generation
```

In terms of *Applying* we need the following:

```gherkin
Scenario: Applying derivatives that were pre-processed
Given an identifer for a FileSet
  And the Pre-processer Lambda has processed the FileSet
When I attach the located <JPGs, HOCRs, Thumbnails> for the split images
Then I will fetch those derivatives from S3
  And attach those derivatives to the FileSet

Scenario: Applying derivatives that were not pre-processed
Given an identifer for a FileSet
  And the Pre-processer Lambda has not processed the FileSet
When I attach the located <JPGs, HOCRs, Thumbnails> for the split images
Then I will generate those derivatives
  And attach those derivatives to the FileSet
```

One consideration is that Hyrax has implicit derivatives that are named concepts; for the above features we need to expose those named concepts.  Namely, how do I locate and apply the thing called `thumbnail`?

</details>

<a id="org11acab4"></a>

# Pre-Process Tasks

Adventist S3 Convention: there’s an AARK unique for each work.  Write files there.

- [ ] https://github.com/scientist-softserv/space_stone-serverless/issues/2
- [ ] https://github.com/scientist-softserv/space_stone-serverless/issues/3
- [ ] https://github.com/scientist-softserv/space_stone-serverless/issues/4
- [ ] https://github.com/scientist-softserv/space_stone-serverless/issues/5
- [x] https://github.com/scientist-softserv/space_stone-serverless/issues/6
- [ ] https://github.com/scientist-softserv/space_stone-serverless/issues/7
- [x] https://github.com/scientist-softserv/space_stone-serverless/issues/8
- [ ] https://github.com/scientist-softserv/space_stone-serverless/issues/9
- [ ] scientist-softserv/adventist_knapsack#398
-   [ ] scientist-softserv/adventist_knapsack#417
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/6
- [x] scientist-softserv/adventist_knapsack#404
- [ ] https://github.com/scientist-softserv/derivative_rodeo/issues/16
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/15
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/17
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/31
-   [x] scientist-softserv/adventist_knapsack#420
    -   We need to write a function that will read an OAI feed and post that to the Pre-processor Lambda.
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/7
- [x] scientist-softserv/adventist_knapsack#399
- [x] scientist-softserv/adventist_knapsack#407 
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/1
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/3
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/2 
-   [x] scientist-softserv/adventist_knapsack#419
    -   Consideration: how is this logic the same/different from what we have in IIIF Print?  What does a canonical function look like?
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/4
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/1
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/2
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/3
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/4
- [x] https://github.com/scientist-softserv/derivative_rodeo/issues/5
- https://github.com/scientist-softserv/derivative-rodeo/issues/5
- https://github.com/scientist-softserv/derivative-rodeo/issues/6
- https://github.com/scientist-softserv/derivative-rodeo/issues/8
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/9
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/10
- [x] https://github.com/scientist-softserv/derivative-rodeo/issues/11

## Ingest Task

- [x] scientist-softserv/adventist_knapsack#406
- [x] https://github.com/scientist-softserv/iiif_print/issues/218
- [ ] https://github.com/scientist-softserv/iiif_print/issues/219
- [ ] https://github.com/scientist-softserv/iiif_print/issues/220

## Task Scratch Pad

Not all of these will be converted to tasks; they instead represent a current workign understanding.  Once we create a task from the checkmark, then we’re looking more at actionable tasks.

- Spike: Establish the S3 bucket organization structure with consideration for: identifier, original file, and derivative type.
- Merge Samvera::Derivatives configuration concerns with IiifPrint configuration
    -   The APIs are not part of production code and provide the named building blocks for this work.
- Rename IiifPrint to Samvera::Derivatives
    -   IiifPrint seems to be a bit of a misnomer; we’re talking about how we want to make derivatives.
-   Space Stone:
    - Run OCR on individual pages
        -   Consideration: how is this logic the same/different from what we have in IIIF Print?  What does a canonical function look like?
    - Generate a thumbnail for each page
        -   Consideration: how is this logic the same/different from what we have in Hyrax?  What does a canonical function look like?
-   Iiif Print:
    - Create general S3 locator function
        -   This needs to account for the derivative type (e.g. `hocr`, `thumbnail`, `splits`, etc) and the identifier.
    - Create general S3 applicator function
        -   This needs to write the file to the location expected by Fedora.  This is behavior that has prior art.
    - Spike: Resolve whether S3 locator pulls file down or if that is the applicator’s purview
Read OAI feed, sending non-thumbnail (and non-reader.pdf) files to S3
