### ISSUE TITLE
Epic: Configure iiif in Adventist

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#440]
# Summary

Once IiifPrint is installed, we should communicate with the client to clarify which configurable features to enable. 

Give the client the options or review their SOW (look in google drive or ask Jill), and update this ticket with what needs to be done.

For PDFs that are split into multiple images (and therefore child works), we don't want those child works to show up in the search.  In other words the expectation is that when searching via `/catalog` they are expecting to find a complete book instead of a heap of loose leaf pages.

We will also need to account for advance search.  The IIIF Print gem recommends using the changes to the [IiifPrint::CatalogSearchBuilder](https://github.com/scientist-softserv/iiif_print/blob/bce83fe49b81b4862ed02e183a3ff240c8e7a5dc/lib/iiif_print/catalog_search_builder.rb).  However, in Adventist they have set the [`CatalogController.search_builder_class` to `AdvSearchBuilder`]( https://github.com/scientist-softserv/adventist-dl/blob/21275bdcf5f50356e0b96ab5d1176195c4effb89/app/controllers/catalog_controller.rb#L50).

*Note:* We will like want to have the `AdvSearchBuilder` inherit from the `IiifPrint::CatalogSearchBuilder`; but we'll need to be cautious about the order of the processor chain because Jeremy has seen the wrong order bungle up queries.

Other considerations will be how we do or do not show the child works in the adminsitrative interface.  Those should be future tickets, as that will be a lower priority than the world-facing tasks.

# Acceptance Criteria

- [x] scientist-softserv/adventist-dl#286
   - [ ] This might require us to create a custom work (ChildPage perhaps?)
   - [ ] We'll need to configure each non-child model to split PDF pages to the ChildPage
- [x] scientist-softserv/adventist_knapsack#436
- [x] scientist-softserv/adventist_knapsack#433
- [ ] Configure Tesseract for OCR scientist-softserv/adventist-dl#248 
- [x] scientist-softserv/adventist_knapsack#432

# Screenshots or Video

# Testing Instructions

# Notes

slack convo: https://assaydepot.slack.com/archives/C0313NJV9PE/p1677254213843829
