### ISSUE TITLE
☄ EPIC: Install Knapsack/Upgrade Hyku

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#540]
# TODO 

- [x] Create a knapsack for adventist, put it up in a new repo
- [x] Go through differences between Hyku v4.0.0~55 and Adventist moving items in to either Hyku main or the knapsack as approriate

  - [x] scientist-softserv/adventist_knapsack#535
  - [x] scientist-softserv/adventist_knapsack#537
  - [x] scientist-softserv/adventist_knapsack#318
  - [x] scientist-softserv/adventist_knapsack#538
  - [x] scientist-softserv/adventist_knapsack#321
  - [x] scientist-softserv/adventist_knapsack#320
  - [x] scientist-softserv/adventist_knapsack#319
  - [x] scientist-softserv/adventist-dl#542
    - [x] scientist-softserv/adventist_knapsack#315
  - [x] scientist-softserv/adventist_knapsack#317
    - [x] scientist-softserv/adventist_knapsack#313
- [x] https://github.com/scientist-softserv/adventist_knapsack/issues/325
- [x] https://github.com/scientist-softserv/adventist_knapsack/issues/324
- [x] https://github.com/scientist-softserv/adventist_knapsack/issues/322
- [x] fix Bugs
- [x] scientist-softserv/adventist_knapsack#316

# NOTES

https://jamboard.google.com/d/1ZjyNbU_CcRj0S9QkS104AFcDIoXQ0sMmFXP1_TmJcco/viewer?f=0

- [x] Upgrade Hyku
**ADL:** 
- hyku version: [3.0.1](https://github.com/scientist-softserv/adventist-dl/blob/main/config/initializers/version.rb#L2)
- Hyrax version: [2.9.6](https://github.com/scientist-softserv/adventist-dl/blob/main/Gemfile.lock#L504)
**Knapsack:**
- hyku version: [5.1.0](https://github.com/samvera/hyku/blob/adventist_dev/config/initializers/version.rb#L2)
- Hyrax version [3.5.0](https://github.com/samvera/hyku/blob/adventist_dev/Gemfile.lock#L579)
