### ISSUE TITLE
💰 Get client approval 

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#544]
To complete after:
- [ ] scientist-softserv/adventist-dl#511
- [x] scientist-softserv/adventist-dl#512 
- [x] scientist-softserv/adventist-dl#513 

# Summary

Clear with @KatharineV the likely cost as well as any timing considerations. 

For example, we have a process to generate a CSV of all of the files in the OAI feed and how to sort them to their correct slot. 

However, there's work being done on the OAI feed, so we want to make sure we catch anything that might be missing.

Generating the OAI CSV will take some time, as it will query through 89,000 records.

# Acceptance Criteria

- [ ] Client reviews our estimates and approves our plan for ingesting ADL data

# Testing Instructions
TBD
