### ISSUE TITLE
☄️ Epic: UV upgrades

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#560]
# Updated Ticket Instructions: May 18, 2023
## Summary
This is an epic 

## Accepted Criteria
- [x] scientist-softserv/adventist_knapsack#387
- [x] scientist-softserv/adventist_knapsack#386
- [x] scientist-softserv/adventist_knapsack#385
- [x] scientist-softserv/adventist_knapsack#384

## Notes

--------------------------------------------------------------------------------------------------------------------------
## Summary
Possible round of work for the future to build out UV on ADL tenants. Wishlist shown in the Accepted Criteria

## Accepted Criteria
~~- [ ] Enable the UV to support multiple search terms~~
~~- [ ] Enable the UV to deliver individual pages as quickly as it does on the example site~~
  - will be covered with derivative rodeo
~~- [ ] Enable individual pages to show with human-readable page numbers, like the example site~~
- [ ] Enable the UV to deliver video--either from an attached file or from YouTube like the example site
- [ ] Enable the UV to deliver audio--if possible
- [ ] Increase the size of the UV on ADL tenants so it displays pages larger upon first load, like it does on the example site
- [ ] Add Download features to the UV on ADL so users can download individual pages or view all pages as PDF/TXT from the action button in the bottom left corner of the UV (see other screenshot for features we'd like, if they're doable)
