### ISSUE TITLE
Run Imports on local environment (QA/follow up)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#566]
# Summary 
We want to test imports on a fresh environment to see if we get any errors

https://assaydepot.slack.com/archives/C0313NJV9PE/p1680103196811269

# Accepted Criteria
- [ ] imports Katharine sent over are run on local environment, documented, and shared with her
- [ ] follow up tickets are created on any errors we run in to
- [ ] Tickets marked 'Data Related' have been looked at and closed if no longer relevant

# Notes

- [x] scientist-softserv/adventist_knapsack#428 
- [x] scientist-softserv/adventist_knapsack#426 
- [x] scientist-softserv/adventist_knapsack#563
