### ISSUE TITLE
Home Page Epic

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist_knapsack#641]
# Summary
**Overarching Goal:** Create a homepage that draws inspiration from the examples below, is more image-heavy/user friendly, has and 'About Us' blurp, and a News Update widget.

Adventist wants to update their homepage to be more image-heavy and friendly for the user. They would also like to have and 'About Us' text on it, and a Widget for News Updates that links to an external site they create. They are taking inspiration from:

- [Atla Digital Library](https://dl.atla.com/)
- [UCLA Library Digital Collections](https://digital.library.ucla.edu/)
- [Anderson University Digital Archives](https://au-archives.hykucommons.org/?locale=en)
- [British Library's Research Repository](https://bl.iro.bl.uk/)

# Accepted Criteria

- [x] [Home Page Wireframes complete](https://gitlab.com/notch8/adventist-dl/-/issues/139)
- [x] [Updated Home Page](https://gitlab.com/notch8/adventist-dl/-/issues/140)
- [x] [Style footer](https://github.com/scientist-softserv/adventist_knapsack/issues/477)
- [x] [Make header & footer color changeable per tenant in appearance styles](https://github.com/scientist-softserv/adventist_knapsack/issues/478)
- [x] [Updated Widget for News](https://gitlab.com/notch8/adventist-dl/-/issues/141)
- [x] [Updated home page text per tenant](https://gitlab.com/notch8/adventist-dl/-/issues/87)
- [x] [Made Banner Image respect a new Banner Image File](https://gitlab.com/notch8/adventist-dl/-/issues/111) 
- [ ] [Bring in feature flipper for Share Work button](https://gitlab.com/notch8/adventist-dl/-/issues/120) 
- [x] [Toolbar for editing content not displaying properly on the Settings -> content block](https://gitlab.com/notch8/adventist-dl/-/issues/81) 
- [x] [Style announcement and alert blocks](https://github.com/scientist-softserv/adventist_knapsack/issues/476)

# Notes
