### ISSUE TITLE
Search Customizations Epic

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist_knapsack#643]
# Summary
Adventist would like the "source," "type," and "date range" facets to open automatically when the search results page loads. They currently have more than one 'date' facet appearing, and would like only one to appear (the 'date created' one). Lastly, they'd like their date range widget to look and function like the widget on Atla's page

# Acceptance Criteria

- [ ] [#143](https://gitlab.com/notch8/adventist-dl/-/issues/143) (Auto-Expanded Facets)
- [ ] [#144](https://gitlab.com/notch8/adventist-dl/-/issues/144) (Facet Type Change for 'Date')
- [ ] [#145](https://gitlab.com/notch8/adventist-dl/-/issues/145) (Update Date Widget)

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)
