### ISSUE TITLE
☄️ Epic: Full Text Search - Highlighted

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist_knapsack#644]
# Summary
Adventist wants full-text search with highlighted search terms in the viewer.
When a user searches for a keyword or phrase, they want the application to return search results in a regular search results format, but include works that contain that keyword or phrase. 

They would also like for the viewer to automatically show the first instance of the search term when a user clicks on the search result and the work page loads. 

They would like to use PDFtron and UV as the viewer.

**Past projects that may be helpful:**

NNP 
- Two step process - search text to get search results, then search in UV on that object to find that area.  Rob: Have to OCR documents w/ coordinates (this is CPU-consuming)

[UCLA Oral Histories uses this](https://oralhistory.library.ucla.edu/)

# Acceptance Criteria

- [x] scientist-softserv/adventist_knapsack#637
- [x] scientist-softserv/adventist_knapsack#389 
- [x] scientist-softserv/adventist_knapsack#588
~~[Imported txt files are re-indexed so the data is available](https://gitlab.com/notch8/adventist-dl/-/issues/147)~~
~~[PDFtron is searchable](https://gitlab.com/notch8/adventist-dl/-/issues/150)~~

# Screenshots or Video

# Testing Instructions

# Notes
- Does this ticket need to be broken down into two tickets?
- How many characters do we want the results of the search terms display?
