### ISSUE TITLE
:comet: SOW: Valkyrization

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#681]
## Summary
**SOW excerpt:** SoftServ will begin by upgrading the ADL to the most recent version of Hyku, which is Knapsack-and-Valkyrie-compatible (pre dynamic support). This work will bring the Valkyrie functionality to ADL, and includes updating the data models for the migration to be successful.

SoftServ estimates 1 sprint to complete these efforts. Prior to development, SoftServ will meet with the
Andrews team to discuss the effort and priority associated with each ticket and outline a viable sprint
plan. One sprint, as defined here, provides for approximately 120 development hours, with project
management and QA. The SoftServ team will point the tickets to share anticipated effort and advise
on what can be accomplished within the sprint, and will undertake the work following prioritization in
collaboration with the Andrews team.

## Tasks
- [x] #695
  - [x] related: https://github.com/scientist-softserv/hykuup_knapsack/issues/232
- [x] #696
  - [x] related: https://github.com/scientist-softserv/hykuup_knapsack/issues/225 
- [x] #687
- [x] #689
- [x] #688
- [x] #690
- [x] https://github.com/scientist-softserv/adventist_knapsack/issues/694
- [x] https://github.com/scientist-softserv/adventist_knapsack/issues/697
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/86
- [x] #715
- [x] #698
- [ ] #716
  - [x] https://github.com/scientist-softserv/adventist_knapsack/issues/711
- [ ] See what's broken

## Acceptance Criteria
- [ ] ADL is on the most recent version of Hyku (v6)
- [ ] ADL can successfully use the Valkyrie functionality to import records

## NOTES
- review steps: https://github.com/scientist-softserv/hykuup_knapsack/issues/35

**Comment by ShanaLMoore** [comment]
todo: get a list of all the files and make a check list

**Comment by jillpe** [comment]
Things to verify in testing:

Importers
- [ ] Can create and import new importers
- [ ] Can edit importers
- [ ] Can delete importers

Data integrity
- [ ] Imported records have correct metadata and data
- [ ] Pre-valkyrie works have correct metadata and data


**Note: 
- the sorting of importers is broken, but they display in alphabetical order. We recommend naming new importers with a 0 at the beginning to send them to the top of the list.
- UV is still broken, so files will not display in a viewer
