### ISSUE TITLE
🦄 Spike: Valkyrize Slugs

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#694]
# Summary

Adventist has a feature that replaces urls with slugs. This only works for Active Fedora objects. We need a slug solution for Valkyrie. 

# Acceptance Criteria

- [ ] Create tickets to implement solutions so Valkyrie objects can be referenced with slugs.

# Tasks
- [ ] :gift: update model SlugBug
    - [x] Remove `slug_for_upgrade`
    - [x] Move iiif_print configuration for slugs to `hyrax.rb`
    - [x] Replace callbacks with listeners or transaction steps
- [ ] :gift: Update module SlugMetadata
    - [x] Remove `slug_for_upgrade`
    - [x] Create slug_metadata yaml file
    - [ ] Determine solution for change of slug predicate - is any migration needed?
- [ ] :gift: Build up `config/initializers/slug_valkyrie_overrides.rb`
    - [ ] Create custom query `FindBySlug`
    - [ ] Override query service `find_by` in `Wings::Valkyrie::QueryService` and `Valkyrie::Persistence::Postgres::QueryService`
- [ ] :unicorn: Determine how to handle finding objects not yet migrated?
  
# Notes

**Comment by laritakr** [comment]
Work to be done here: https://github.com/scientist-softserv/adventist_knapsack/issues/713
