### ISSUE TITLE
🎁 Valkyrize Slugs

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#713]
# Summary

Adventist has a feature that replaces urls with slugs. This only works for Active Fedora objects. We need a slug solution for Valkyrie. 

Ref #694

# Tasks

- [x] :gift: update model SlugBug
    - [x] Remove `slug_for_upgrade`
    - [x] Move iiif_print configuration for slugs to `hyrax.rb`
    - [x] Replace callbacks with listeners or transaction steps
- [x] :gift: Update module SlugMetadata
    - [x] Remove `slug_for_upgrade`
    - [x] Create slug_metadata yaml file
    - [ ] Determine solution for change of slug predicate - is any migration needed?
- [x] :gift: Build up `config/initializers/slug_valkyrie_overrides.rb`
    - [x] Create custom query `FindBySlug`
    - [x] Override query service `find_by` in `Wings::Valkyrie::QueryService` and `Valkyrie::Persistence::Postgres::QueryService`
- [ ] :unicorn: Determine how to handle finding objects not yet migrated?

# Acceptance Criteria

# Testing Instructions
Create a work with an aark id and save. Notice that aark_id becomes the slug for this work. Take note of the slug url.
Using the same work, try: 
- Updating the aark id. Does the slug url change?
- Removing the aark id. Does the slug get removed from the URL?

# Notes
A very rough WIP branch is underway.

**Comment by ShanaLMoore** [comment]
cc @laritakr Could you clarify the acceptance criteria and testing instructions for this ticket?

**Comment by ShanaLMoore** [comment]
# QA RESULTS: ⚠ PENDING
